# Stage 1: Build dependencies
FROM node:18-alpine AS builder

WORKDIR /app

COPY package.json ./
RUN npm install --omit=dev

COPY . .

# Stage 2: Minimal Distroless image
FROM gcr.io/distroless/nodejs18-debian11

WORKDIR /app

COPY --from=builder /app .

CMD ["server.js"]

