---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: hit-counter-app
spec:
  selector:
    app: frontend-service
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: hit-logger-service
  namespace: hit-counter-app
spec:
  selector:
    app: hit-logger-service
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: hit-counter-service
  namespace: hit-counter-app
spec:
  selector:
    app: hit-counter-service
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP
---